<script setup>

</script>

<template>
    <b-skeleton animation="wave" width="85%"></b-skeleton>
    <b-skeleton animation="wave" width="55%"></b-skeleton>
    <b-skeleton animation="wave" width="70%"></b-skeleton>
    <b-skeleton animation="wave" width="85%"></b-skeleton>
    <b-skeleton animation="wave" width="55%"></b-skeleton>
    <b-skeleton animation="wave" width="70%"></b-skeleton>
    <b-skeleton animation="wave" width="85%"></b-skeleton>
    <b-skeleton animation="wave" width="55%"></b-skeleton>
    <b-skeleton animation="wave" width="70%"></b-skeleton>
    <b-skeleton animation="wave" width="85%"></b-skeleton>
    <b-skeleton animation="wave" width="55%"></b-skeleton>
    <b-skeleton animation="wave" width="70%"></b-skeleton>
    <b-skeleton animation="wave" width="85%"></b-skeleton>
    <b-skeleton animation="wave" width="55%"></b-skeleton>
    <b-skeleton animation="wave" width="70%"></b-skeleton>
    <b-skeleton animation="wave" width="85%"></b-skeleton>
    <b-skeleton animation="wave" width="55%"></b-skeleton>
    <b-skeleton animation="wave" width="70%"></b-skeleton>
    <b-skeleton animation="wave" width="85%"></b-skeleton>
    <b-skeleton animation="wave" width="55%"></b-skeleton>
    <b-skeleton animation="wave" width="70%"></b-skeleton>
    <b-skeleton animation="wave" width="85%"></b-skeleton>
    <b-skeleton animation="wave" width="55%"></b-skeleton>
    <b-skeleton animation="wave" width="70%"></b-skeleton>
    <b-skeleton animation="wave" width="85%"></b-skeleton>
    <b-skeleton animation="wave" width="55%"></b-skeleton>
    <b-skeleton animation="wave" width="70%"></b-skeleton>
    <b-skeleton animation="wave" width="85%"></b-skeleton>
    <b-skeleton animation="wave" width="55%"></b-skeleton>
    <b-skeleton animation="wave" width="70%"></b-skeleton>
    <b-skeleton animation="wave" width="85%"></b-skeleton>
    <b-skeleton animation="wave" width="55%"></b-skeleton>
    <b-skeleton animation="wave" width="70%"></b-skeleton>
    <b-skeleton animation="wave" width="85%"></b-skeleton>
    <b-skeleton animation="wave" width="55%"></b-skeleton>
    <b-skeleton animation="wave" width="70%"></b-skeleton>
    <b-skeleton animation="wave" width="85%"></b-skeleton>
    <b-skeleton animation="wave" width="55%"></b-skeleton>
    <b-skeleton animation="wave" width="70%"></b-skeleton>
    <b-skeleton animation="wave" width="85%"></b-skeleton>
    <b-skeleton animation="wave" width="55%"></b-skeleton>
    <b-skeleton animation="wave" width="70%"></b-skeleton>
    <b-skeleton animation="wave" width="85%"></b-skeleton>
    <b-skeleton animation="wave" width="55%"></b-skeleton>
    <b-skeleton animation="wave" width="70%"></b-skeleton>
    <b-skeleton animation="wave" width="85%"></b-skeleton>
    <b-skeleton animation="wave" width="55%"></b-skeleton>
    <b-skeleton animation="wave" width="70%"></b-skeleton>
    <b-skeleton animation="wave" width="85%"></b-skeleton>
    <b-skeleton animation="wave" width="55%"></b-skeleton>
    <b-skeleton animation="wave" width="70%"></b-skeleton>
    <b-skeleton animation="wave" width="85%"></b-skeleton>
    <b-skeleton animation="wave" width="55%"></b-skeleton>
    <b-skeleton animation="wave" width="70%"></b-skeleton>
    <b-skeleton animation="wave" width="85%"></b-skeleton>
    <b-skeleton animation="wave" width="55%"></b-skeleton>
    <b-skeleton animation="wave" width="70%"></b-skeleton>
    <b-skeleton animation="wave" width="85%"></b-skeleton>
    <b-skeleton animation="wave" width="55%"></b-skeleton>
    <b-skeleton animation="wave" width="70%"></b-skeleton>
    <b-skeleton animation="wave" width="85%"></b-skeleton>
    <b-skeleton animation="wave" width="55%"></b-skeleton>
    <b-skeleton animation="wave" width="70%"></b-skeleton>
    <b-skeleton animation="wave" width="85%"></b-skeleton>
    <b-skeleton animation="wave" width="55%"></b-skeleton>
    <b-skeleton animation="wave" width="70%"></b-skeleton>
    <b-skeleton animation="wave" width="85%"></b-skeleton>
    <b-skeleton animation="wave" width="55%"></b-skeleton>
    <b-skeleton animation="wave" width="70%"></b-skeleton>
    <b-skeleton animation="wave" width="85%"></b-skeleton>
    <b-skeleton animation="wave" width="55%"></b-skeleton>
    <b-skeleton animation="wave" width="70%"></b-skeleton>
</template>